name = "zenith-core"
author = "ZekeZ"
version = "development"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25e2dcca6dcb7c1063f631fce7315e829101ad1123d9aa7a9f48150176c92510"

[versions]
minecraft = "1.18.2"
quilt = "0.18.1-beta.16"

[options]
meta-folder-base = "meta"
