name = "Rainbow"
author = "Prism Community"
version = "develop"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec8bc1ee73e996bcf34fe48f0e8411f6f27736189d9d0cb6e5067ffbc99dac45"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
