name = "zapp"
author = "ZekeZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32ecda85f7ef27478b280d0d904566c2189f41c2457504d964b401a227ffcd23"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
