name = "warp-core"
author = "ZekeZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0964a07fea4916af4f97261134963f6a7f6b5cd7504fdd747dd19ac0345c3dc6"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
