name = "warp-core"
author = "ZekeZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3649b90af26d54e3c670b50ff9650a16a7432e102310604980a2884bc01b69e0"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
