name = "warp-core"
author = "ZekeZ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45ea60aa33c3586fff608c3851367d1006920b02b7844538baf1fd5340455208"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
