name = "warp-core"
author = "ZekeZ"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "721ee61eb172d7059820cf0454c3766f2c52c26a6bb4206571d289469abba447"

[versions]
minecraft = "1.19.2"
quilt = "0.18.10"
