name = "rainbow"
author = "Prism Community"
version = "1.0.4-1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc77b05e21288c5b7e6c4873f16da5b47d5d4b26ddf55ff30cd99bb91e18bb08"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
