name: Build Modpack

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: 
          go-version: '1.18'
          check-latest: true

      - name: Download Dependencys
        run: |
          sudo apt install git p7zip
          go install github.com/packwiz/packwiz@latest

      - name: Make Modrinth
        run: |
          make modrinth
          7z x zenith-core-development.mrpack -o.modrinth

      - name: Make Prism Develop
        run: |
          make prism
          7z x modpack-prism.zip -o.prism

      - name: Make Server
        run: |
          make server

      - name: Upload Modrinth
        uses: actions/upload-artifact@v3
        with:
          name: HexMC Modrinth
          path: .modrinth

      - name: Upload Prism (Development)
        uses: actions/upload-artifact@v3
        with:
          name: Zenith-Core Prism Development
          path: .prism

      - name: Upload Server
        uses: actions/upload-artifact@v3
        with:
          name: Zenith-Core Server
          path: server