name: Build Modpack

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/gradle-build-action@v2
      - uses: actions/setup-go@v3
        with: 
          go-version: '1.18'
          check-latest: true

      - name: Download Dependencys
        run: |
          sudo apt install git p7zip
          go install github.com/packwiz/packwiz@latest

      - name: Make Modrinth
        run: |
          make modrinth
          7z x zenith-core-development.mrpack -o .modrinth

      - name: Make Server
        run: |
          make server
          7z x server.mrpack -o .server

      - name: Upload Modrinth
        uses: actions/upload-artifact@v3
        with:
          name: HexMC Modrinth
          path: build/.modrinth

      - name: Upload Modrinth
        uses: actions/upload-artifact@v3
        with:
          name: HexMC Modrinth
          path: build/.modrinth
          
      - name: Upload PolyMC (Auto Update)
        uses: actions/upload-artifact@v3
        with:
          name: HexMC MultiMC-PolyMC Auto Update
          path: build/.polymc