name: Build Modpack

on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with: 
          go-version: '1.18'
          check-latest: true

      - name: Download Dependencys
        run: |
          sudo apt install git p7zip make
          go install github.com/packwiz/packwiz@latest

      - name: Make Modrinth
        run: |
          make modrinth
          7z x modpack-modrinth.mrpack -o./build/.modrinth

      - name: Publish .mrpack
        uses: RyanModDev/mrpack-publish@v0
        with:
          name: HexMC
          version-number: 5.0.0-testing
          project-id: AyAXUE4r
          pack-filename: modpack-modrinth.mrpack
          game-versions: 1.18.2
          loaders: quilt
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}