name: Build Modpack

on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
      - uses: actions/setup-go@v3
        with: 
          go-version: '1.18'
          check-latest: true

      - name: Download Dependencys
        run: |
          sudo apt install git p7zip make
          go install github.com/packwiz/packwiz@latest

      - name: Make Modrinth
        run: |
          make modrinth
          7z x ./build/modpack-modrinth.mrpack -o./build/.modrinth

      - name: Make PolyMC (Auto Update)
        run: |
          make polymc
          7z x ./build/modpack-polymc.zip -o./build/.polymc

      - name: Make Server (Auto Update)
        run: |
          make hexserver
          7z x ./build/modpack-server.zip -o./build/.server

      - name: Upload Modrinth
        uses: actions/upload-artifact@v3
        with:
          name: HexMC Modrinth
          path: build/.modrinth
          
      - name: Upload PolyMC (Auto Update)
        uses: actions/upload-artifact@v3
        with:
          name: HexMC MultiMC-PolyMC Auto Update
          path: build/.polymc

      - name: Upload Server (Auto Update)
        uses: actions/upload-artifact@v3
        with:
          name: Auto Update Server
          path: build/.server

      - name: Publish .mrpack
        uses: Warped-Modding/mrpack-publish@v0
        with:
          name: HexMC
          version-number: 5.0.0-testing
          project-id: AyAXUE4r
          pack-filename: modpack-modrinth
          game-versions: 1.18.2
          loaders: Quilt
          modrinth-token: ${{ secrets.AZURE_CREDENTIALS }}